name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v4
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target-branch: main
        config-file: release-please-config.json
        manifest-file: release-please-manifest.json

    - name: Publish
      uses: './.github/workflows/publish.yml'
      if: ${{ steps.release.outputs.release_created }}