name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v4
      id: release
      with:
        release-type: node
        token: ${{ secrets.GITHUB_TOKEN }}
        default-branch: main

    - name: Publish
      uses: './.github/workflows/publish.yml'
      if: ${{ steps.release.outputs.release_created }}